// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VApp.Entity
{
    [Keyless]
    [Table("Employee")]
    public partial class Employee
    {
        public string employeeID { get; set; }
        public string employeeName { get; set; }
        public string email { get; set; }
        [StringLength(50)]
        public string mobileNumber { get; set; }
        public string address { get; set; }
        [Column(TypeName = "date")]
        public DateTime? joiningDate { get; set; }
        public string designation { get; set; }
        [StringLength(10)]
        public string gender { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DOB { get; set; }
    }
}