// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VApp.Entity
{
    [Table("Family")]
    public partial class Family
    {
        [Key]
        public int SNO { get; set; }
        [StringLength(20)]
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string PersonName { get; set; }
        public string Relationship { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DOB { get; set; }
        [StringLength(20)]
        public string Gender { get; set; }
        [StringLength(50)]
        public string IsAffected { get; set; }
        [Column(TypeName = "date")]
        public DateTime? AffectedDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? RecoveryDate { get; set; }
        [StringLength(50)]
        public string IsVaccinated { get; set; }
        [Column(TypeName = "date")]
        public DateTime? VaccinatedDateOne { get; set; }
        public string CertificateOne { get; set; }
        [Column(TypeName = "date")]
        public DateTime? VaccinatedDateTwo { get; set; }
        public string CertificateTwo { get; set; }
        public string VaccineName { get; set; }
        [StringLength(50)]
        public string DoseOne { get; set; }
        [StringLength(50)]
        public string DoseTwo { get; set; }
    }
}