// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VApp.Entity
{
    [Keyless]
    [Table("Login")]
    public partial class Login
    {
        public string EmployeeID { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    }
}