// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VApp.Entity
{
    public partial class sp_loginResult
    {
        public string EmployeeID { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    }
}
