// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VApp.Entity
{
    [Table("Vaccine")]
    public partial class Vaccine
    {
        [Key]
        public int SNO { get; set; }
        [StringLength(100)]
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string VaccineName { get; set; }
        [StringLength(50)]
        public string DoseOne { get; set; }
        [StringLength(50)]
        public string DoseTwo { get; set; }
        [Column(TypeName = "date")]
        public DateTime? VaccinationDateOne { get; set; }
        [Column(TypeName = "date")]
        public DateTime? VaccinationDateTwo { get; set; }
        public string CertificateOne { get; set; }
        public string CertificateTwo { get; set; }
        [StringLength(50)]
        public string IsAffected { get; set; }
        [Column(TypeName = "date")]
        public DateTime? AffectedDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? RecoveryDate { get; set; }
        public int? RecoveryDuration { get; set; }
        [StringLength(50)]
        public string IsVaccinated { get; set; }
    }
}