// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace VApp.Entity
{
    public partial class VAContext : DbContext
    {
        public VAContext()
        {
        }

        public VAContext(DbContextOptions<VAContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Family> Families { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Vaccine> Vaccines { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Employee>(entity =>
            {
                entity.Property(e => e.address).IsUnicode(false);

                entity.Property(e => e.designation).IsUnicode(false);

                entity.Property(e => e.email).IsUnicode(false);

                entity.Property(e => e.employeeID).IsUnicode(false);

                entity.Property(e => e.employeeName).IsUnicode(false);

                entity.Property(e => e.gender).IsUnicode(false);

                entity.Property(e => e.mobileNumber).IsUnicode(false);
            });

            modelBuilder.Entity<Family>(entity =>
            {
                entity.HasKey(e => e.SNO)
                    .HasName("PK__Family__CA1EE06C7DCCBAA5");

                entity.Property(e => e.CertificateOne).IsUnicode(false);

                entity.Property(e => e.CertificateTwo).IsUnicode(false);

                entity.Property(e => e.DoseOne).IsUnicode(false);

                entity.Property(e => e.DoseTwo).IsUnicode(false);

                entity.Property(e => e.EmployeeID).IsUnicode(false);

                entity.Property(e => e.EmployeeName).IsUnicode(false);

                entity.Property(e => e.Gender).IsUnicode(false);

                entity.Property(e => e.IsAffected).IsUnicode(false);

                entity.Property(e => e.IsVaccinated).IsUnicode(false);

                entity.Property(e => e.PersonName).IsUnicode(false);

                entity.Property(e => e.Relationship).IsUnicode(false);

                entity.Property(e => e.VaccineName).IsUnicode(false);
            });

            modelBuilder.Entity<Login>(entity =>
            {
                entity.Property(e => e.EmployeeID).IsUnicode(false);

                entity.Property(e => e.Password).IsUnicode(false);

                entity.Property(e => e.Role).IsUnicode(false);
            });

            modelBuilder.Entity<Vaccine>(entity =>
            {
                entity.HasKey(e => e.SNO)
                    .HasName("PK__Vaccine__CA1EE06CD2DDF6AF");

                entity.Property(e => e.CertificateOne).IsUnicode(false);

                entity.Property(e => e.CertificateTwo).IsUnicode(false);

                entity.Property(e => e.DoseOne).IsUnicode(false);

                entity.Property(e => e.DoseTwo).IsUnicode(false);

                entity.Property(e => e.EmployeeID).IsUnicode(false);

                entity.Property(e => e.EmployeeName).IsUnicode(false);

                entity.Property(e => e.IsAffected).IsUnicode(false);

                entity.Property(e => e.IsVaccinated).IsUnicode(false);

                entity.Property(e => e.VaccineName).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}