// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VApp.Entities
{
    [Table("AffectedEmployee")]
    public partial class AffectedEmployee
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("empId")]
        public int EmpId { get; set; }
        [Column("isRecoveryed")]
        public bool IsRecoveryed { get; set; }
        [Column("recoveryDuration")]
        public int? RecoveryDuration { get; set; }
        [Column("isFamilyAffected")]
        public bool IsFamilyAffected { get; set; }
    }
}