// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VApp.Entities
{
    public partial class AffectedFamilyDetail
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("empId")]
        public int EmpId { get; set; }
        [Required]
        [Column("memberName")]
        public string MemberName { get; set; }
        [Column("isRecoveryed")]
        public bool IsRecoveryed { get; set; }
        [Column("recoveryDuration")]
        public int? RecoveryDuration { get; set; }
        [Column("relationshipId")]
        public int? RelationshipId { get; set; }

        [ForeignKey(nameof(RelationshipId))]
        [InverseProperty(nameof(RelationshipType.AffectedFamilyDetails))]
        public virtual RelationshipType Relationship { get; set; }
    }
}