// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VApp.Entities
{
    public partial class District
    {
        public District()
        {
            Taluks = new HashSet<Taluk>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        public string Name { get; set; }
        [Column("code")]
        [StringLength(20)]
        public string Code { get; set; }
        [Column("countryId")]
        public int? CountryId { get; set; }
        [Column("stateId")]
        public int? StateId { get; set; }

        [ForeignKey(nameof(StateId))]
        [InverseProperty("Districts")]
        public virtual State State { get; set; }
        [InverseProperty(nameof(Taluk.District))]
        public virtual ICollection<Taluk> Taluks { get; set; }
    }
}