// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VApp.Entities
{
    public partial class DoseType
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("doseType")]
        public int DoseType1 { get; set; }
    }
}