// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VApp.Entities
{
    public partial class RelationshipType
    {
        public RelationshipType()
        {
            AffectedFamilyDetails = new HashSet<AffectedFamilyDetail>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("typeName")]
        [StringLength(50)]
        public string TypeName { get; set; }

        [InverseProperty(nameof(AffectedFamilyDetail.Relationship))]
        public virtual ICollection<AffectedFamilyDetail> AffectedFamilyDetails { get; set; }
    }
}