// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VApp.Entities
{
    public partial class RoleType
    {
        public RoleType()
        {
            Employees = new HashSet<Employee>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("typeName")]
        [StringLength(70)]
        public string TypeName { get; set; }

        [InverseProperty(nameof(Employee.Role))]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}