// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VApp.Entities
{
    public partial class sp_getAllDoseTypesResult
    {
        public int id { get; set; }
        public int doseType { get; set; }
    }
}
