// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VApp.Entities
{
    public partial class sp_getAllTaluksResult
    {
        public int id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string stateName { get; set; }
        public string districtName { get; set; }
        public string countryName { get; set; }
    }
}
