// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VApp.Entities
{
    public partial class sp_getAffectedFamilydetailsResult
    {
        public int id { get; set; }
        public int empId { get; set; }
        public string memberName { get; set; }
        public bool isRecoveryed { get; set; }
        public int? recoveryDuration { get; set; }
        public string typeName { get; set; }
    }
}
