// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VApp.Entities
{
    public partial class sp_getAllAffectedEmployeeResult
    {
        public int id { get; set; }
        public string empName { get; set; }
        public string code { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
        public DateTime joiningDate { get; set; }
        public bool isRecoveryed { get; set; }
        public int? recoveryDuration { get; set; }
        public bool isFamilyAffected { get; set; }
    }
}
