// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VApp.Entities
{
    public partial class sp_loginResult
    {
        public int id { get; set; }
        public string code { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
        public DateTime joiningDate { get; set; }
        public DateTime? relesaeDate { get; set; }
        public int createdBy { get; set; }
        public DateTime createdOn { get; set; }
        public int? updatedBy { get; set; }
        public DateTime? updatedOn { get; set; }
        public bool? statusFlag { get; set; }
        public string password { get; set; }
        public int? roleId { get; set; }
        public int? reportingManagerId { get; set; }
        public int? bgId { get; set; }
        public int? designationId { get; set; }
        public int? countryId { get; set; }
        public int? stateId { get; set; }
        public int? districtId { get; set; }
        public int? talukId { get; set; }
    }
}
