// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VApp.Entities
{
    public partial class sp_vaccinationDetailsResult
    {
        public int id { get; set; }
        public string name { get; set; }
        public int doseType { get; set; }
        public string hospitalName { get; set; }
        public string certificatePath { get; set; }
        public DateTime? vaccinationDate { get; set; }
        public string state { get; set; }
        public string district { get; set; }
        public string taluk { get; set; }
    }
}
