// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace VApp.Entities
{
    public partial class VaccinationDetail
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("empId")]
        public int EmpId { get; set; }
        [Column("vccineNameId")]
        public int? VccineNameId { get; set; }
        [Column("doseTypeId")]
        public int? DoseTypeId { get; set; }
        [Column("vaccinationDate", TypeName = "date")]
        public DateTime? VaccinationDate { get; set; }
        [Column("stateId")]
        public int? StateId { get; set; }
        [Column("districtId")]
        public int? DistrictId { get; set; }
        [Column("talukId")]
        public int? TalukId { get; set; }
        [Column("hospitalName")]
        public string HospitalName { get; set; }
        [Column("certificatePath")]
        public string CertificatePath { get; set; }
    }
}